version: '3'

services:
  tic-tac-toe-app:
    container_name: tic-tac-toe-app
    image: task/tic-tac-toe-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"